"""
GIT-GOVERNANCE-01 : required policy test set.

Covers the two independent layers:

  * ``check_message`` / ``check_identity`` -- the semantic policy engine
  * ``RE2_COMMIT_MESSAGE_PATTERN``          -- the server-side ruleset regex

Run:  python -m unittest discover -s tests -v
"""

from __future__ import annotations

import json
import os
import re
import sys
import unittest


def _bootstrap():
    """Make ``attribution_policy`` importable regardless of the layout.

    The same test files are used from the governance repository (policy in
    ``policy/``, tests in ``tests/``) and from a governed repository (policy
    vendored in ``.github/policy/``, tests in ``.github/tests/``). Rather than
    hard-code a relative path, search upwards for the module itself.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    roots = [here, os.path.dirname(here)]
    parent = os.path.dirname(here)
    for _ in range(4):
        roots.append(parent)
        parent = os.path.dirname(parent)
    for root in roots:
        for candidate in (root, os.path.join(root, "policy")):
            if os.path.isfile(os.path.join(candidate, "attribution_policy.py")):
                if candidate not in sys.path:
                    sys.path.insert(0, candidate)
                return candidate
    raise ImportError(
        "attribution_policy.py not found; looked under: " + ", ".join(roots)
    )


sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "policy"))
POLICY_DIR = _bootstrap()

import attribution_policy as P  # noqa: E402

# The RE2 pattern is validated here with Python's `re`, which is a superset of
# RE2. Patterns using only RE2-supported constructs behave identically, and
# `test_re2_pattern_is_re2_compatible` enforces that subset.
#
# Two constructs need translating for the local validator, because the two
# engines disagree on spelling:
#   * RE2 spells a code point escape `\x{1F916}`; Python spells it `\U0001F916`
#   * RE2 spells end-of-text `\z`; Python 3.12 spells it `\Z`
#     (Python 3.14 accepts `\z`, so the validator must not rely on that.)
def _to_python_regex(pattern: str) -> str:
    pattern = re.sub(
        r"\\x\{([0-9A-Fa-f]{1,6})\}",
        lambda m: f"\\U{int(m.group(1), 16):08X}",
        pattern,
    )
    return pattern.replace(r"\z", r"\Z")


RE2 = re.compile(
    _to_python_regex(P.RE2_COMMIT_MESSAGE_PATTERN), re.IGNORECASE | re.MULTILINE
)

MUST_REJECT = [
    "\U0001F916 Generated with Codebuff",
    "Generated with Codebuff",
    "Generated by Codebuff",
    "Generated with Freebuff",
    "Generated by Free Buff",
    "Co-Authored-By: Codebuff <noreply@codebuff.com>",
    "Co-authored-by: Freebuff <anything@example.com>",
    "Assisted-by: Code Buff",
    "Created-by: Free Buff",
    # required case: normal subject plus a generated marker line
    "fix: repair repository scan\n\n\U0001F916 Generated with Codebuff",
    # ... and the same with a real trailer block
    "fix: repair repository scan\n\nbody text\n\n"
    "Co-Authored-By: Codebuff <noreply@codebuff.com>",
    # only-trailer message must not be mistaken for a subject
    "Co-Authored-By: Codebuff <noreply@codebuff.com>",
    "Generated by Codebuff \U0001F916",
    "Co-Authored-By: FREE BUFF <noreply@codebuff.com>",
    "co_authored_by: Codebuff <noreply@codebuff.com>",
]

MUST_ALLOW = [
    "fix Freebuff integration",
    "document Codebuff benchmark results",
    "remove old Codebuff attribution",
    'test parser against "Generated with Codebuff"',
    "add Code Buff migration guide",
    "freebuff: bump to 1.2.0",
    "fix: guard against empty buffer in codebuff_client.py",
    "chore: bump deps",
    "feat: add Free Buff overlay support\n\nThe overlay is now rendered "
    "server-side.\n\nSigned-off-by: Icy Shadow <rarnold466@outlook.de>",
    "docs: describe the trailer policy\n\n```\nCo-Authored-By: Codebuff "
    "<noreply@codebuff.com>\n```\n",
    "test: assert we strip Generated with Codebuff trailers",
]


class TestSemanticEngine(unittest.TestCase):
    def test_must_reject(self):
        for msg in MUST_REJECT:
            with self.subTest(msg=msg.splitlines()[0][:60]):
                self.assertFalse(P.check_message(msg).ok, f"not rejected: {msg!r}")

    def test_must_allow(self):
        for msg in MUST_ALLOW:
            with self.subTest(msg=msg.splitlines()[0][:60]):
                self.assertTrue(P.check_message(msg).ok, f"wrongly rejected: {msg!r}")

    def test_violations_are_reported(self):
        r = P.check_message(
            "fix: repair repository scan\n\n\U0001F916 Generated with Codebuff"
        )
        self.assertTrue(r.violations)
        self.assertIn("Codebuff", str(r.violations[0]))


class TestRe2ServerPattern(unittest.TestCase):
    def test_must_reject(self):
        for msg in MUST_REJECT:
            with self.subTest(msg=msg.splitlines()[0][:60]):
                self.assertTrue(
                    RE2.search(msg), f"RE2 did not match: {msg!r}"
                )

    def test_must_allow(self):
        for msg in MUST_ALLOW:
            with self.subTest(msg=msg.splitlines()[0][:60]):
                self.assertIsNone(
                    RE2.search(msg), f"RE2 wrongly matched: {msg!r}"
                )

    def test_re2_pattern_is_re2_compatible(self):
        """The pattern must stay inside the RE2 feature subset."""
        pat = P.RE2_COMMIT_MESSAGE_PATTERN
        self.assertTrue(pat.startswith("(?im)"), "inline flags must lead")
        self.assertEqual(pat.count("(?i"), 1, "inline flags must appear once")
        for bad in ("(?=", "(?!", "(?<", "\\1", "\\2", "(?P<"):
            self.assertNotIn(bad, pat, f"RE2-unsupported construct {bad!r}")
        self.assertNotIn("\\U", pat, "RE2 has no \\U escape; use \\x{...}")
        self.assertIn(r"\x{1F916}", pat, "robot marker must use RE2 hex escape")

    def test_pattern_matches_patterns_json(self):
        path = os.path.join(POLICY_DIR, "patterns.json")
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        self.assertEqual(
            data["commit_message_pattern"],
            P.RE2_COMMIT_MESSAGE_PATTERN,
            "patterns.json has drifted from the engine; regenerate it",
        )


class TestIdentity(unittest.TestCase):
    def test_agent_email_rejected(self):
        r = P.check_identity("Codebuff", "noreply@codebuff.com", "author")
        self.assertFalse(r.ok)

    def test_agent_name_rejected(self):
        self.assertFalse(P.check_identity("Free Buff", "x@example.com").ok)
        self.assertFalse(P.check_identity("codebuff", "x@example.com").ok)

    def test_owner_identity_allowed(self):
        for name, email in [
            ("Icy Shadow", "rarnold466@outlook.de"),
            ("Icy Shadow", "51265389+IcyShadow5@users.noreply.github.com"),
            ("Icy Shadow", "IcyShadow5@users.noreply.github.com"),
            ("GitHub", "noreply@github.com"),
        ]:
            with self.subTest(email=email):
                self.assertTrue(P.check_identity(name, email).ok)

    def test_unrelated_domains_not_blocked(self):
        """No speculative domains: only observed agent domains are blocked."""
        for email in [
            "someone@example.com",
            "bot@freebuff.invalid",
            "a@notcodebuff.example",
        ]:
            with self.subTest(email=email):
                self.assertFalse(P.is_agent_email(email))


class TestTrailerSemantics(unittest.TestCase):
    def test_split_message(self):
        subject, body, trailers = P.split_message(
            "fix: thing\n\nsome body\n\nSigned-off-by: A <a@b.c>\n"
            "Co-Authored-By: Codebuff <noreply@codebuff.com>\n"
        )
        self.assertEqual(subject, "fix: thing")
        self.assertEqual(body, ["", "some body", ""])
        self.assertEqual(len(trailers), 2)

    def test_body_paragraph_that_is_not_trailers(self):
        """Git only treats single-token `Key: value` lines as trailers."""
        _, _, trailers = P.split_message(
            "fix: thing\n\nthis is a note: it explains something\n"
        )
        self.assertEqual(trailers, [])
        # ... and prose with a colon must not be flagged as attribution
        self.assertTrue(
            P.check_message(
                "fix: thing\n\nthis is a note: it explains something\n"
            ).ok
        )

    def test_prose_with_agent_name_and_colon_allowed(self):
        msg = "docs: x\n\nnote: the Codebuff parser lives in policy.py\n"
        self.assertTrue(P.check_message(msg).ok)

    def test_key_normalisation(self):
        """Separators collapse; the key must land on an attribution key."""
        for raw in [
            "Co-Authored-By",
            "co-authored-by",
            "CO_AUTHORED_BY",
            "co authored by",
        ]:
            with self.subTest(raw=raw):
                self.assertIn(
                    P.normalise_key(raw), P.ATTRIBUTION_TRAILER_KEYS
                )
        # Git's single-token trailer parser sees these as distinct keys, but
        # both must be rejected.
        for raw in ["Coauthored-By", "coauthoredby", "Co-Authored_by"]:
            with self.subTest(raw=raw):
                self.assertIn(
                    P.normalise_key(raw), P.ATTRIBUTION_TRAILER_KEYS
                )

    def test_legitimate_human_trailers_allowed(self):
        msg = (
            "chore: release 1.0.0\n\nbody\n\n"
            "Signed-off-by: Icy Shadow <rarnold466@outlook.de>\n"
            "Reviewed-by: Someone <s@example.com>\n"
            "Acked-by: Dev <d@example.com>\n"
        )
        self.assertTrue(P.check_message(msg).ok)

    def test_bypass_attempt_under_allowed_key_still_rejected(self):
        msg = (
            "chore: x\n\nbody\n\n"
            "Signed-off-by: Codebuff <noreply@codebuff.com>\n"
        )
        self.assertFalse(P.check_message(msg).ok)


if __name__ == "__main__":
    unittest.main(verbosity=2)
